name: pip_flutter_example
description: Demonstrates how to use the pip_flutter plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.20.0"

dependencies:
  flutter:
    sdk: flutter
  pip_flutter:
    path: ../
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
