name: pip_flutter
description: A new Flutter Picture in Picture Package for android.When app is running in foregorund that time also app not kill.
version: 0.0.3
homepage: https://github.com/kesmitopiwala/pip_flutter/blob/master/example/lib/main.dart

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  wakelock: ^0.5.6
  visibility_detector: ^0.2.0
  xml: ^5.3.0
  pedantic: ^1.11.1
  flutter_widget_from_html_core: ^0.8.2
  path_provider: ^2.0.5
  collection: ^1.15.0

dependency_overrides:
  win32: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.pip_flutter
        pluginClass: PipFlutterPlugin
      ios:
        pluginClass: PipFlutterPlugin

  assets:
   - assets/